my changes
coderbunker/nuodata-example pull request #1
Opened 2017-01-06 07:18 UTC by Aesirry

2017-01-06 12:28 UTC, rngadam requested changes
* Don't put sensitive values in commit history
* Apply defensive programming practices
* More descriptive commit messages, pull requests names, function names ("my changes", "jdevelop", "practice.xlsx") are all meaningless names with no value

2017-01-06 12:28 UTC, rngadam commented on excel.py
> +        result = urllib.parse.urlparse("postgres://4cebab44:4j602JWnaP3Yaw@db.nuodata.io:5432/4cebab44")
NEVER put authentication information in a git history. 

Easiest is to put it into a separate user-created JSON file and use built-in JSON parsing support.

```
rngadam@rngadam-mac ~/c/s/nuodata-example> cat config.json 
{
    "username": "USERNAME",
    "password": "PASSWORD"
}
rngadam@rngadam-mac ~/c/s/nuodata-example> python
>>> import json
>>> c = json.load(open('config.json'))
>>> c['username']
u'USERNAME'
>>> c['password']
u'PASSWORD'
```

Make sure to put config.json in .gitignore and create a config.json.example.

2017-01-06 12:28 UTC, rngadam commented on excel.py
> +        print("<couldn't connect>")
You've just created a function connect() that silently fails if a failure happens.

Best practice is to capture and log the full error information and rethrow a custom exception to force the caller to handle it.

2017-01-06 12:28 UTC, rngadam commented on excel.py
> +    wb = xlrd.open_workbook('practice.xlsx')
Much less reusable if you put plain constant strings within a function. make 'practice.xlsx' a function parameter.

2017-01-06 12:28 UTC, rngadam commented on excel.py
> +        c.execute("INSERT INTO test (name, age) VALUES (%s, %s)", (item['name'], item['age']))
better error handling required, read this:

http://stackoverflow.com/questions/8497886/graceful-primary-key-error-handling-in-python-psycopg2

2017-01-06 12:29 UTC, rngadam commented
update the README.md to explain what this does, put references and give usage example

2017-01-08 01:33 UTC, Aesirry commented on excel.py
> +    wb = xlrd.open_workbook('practice.xlsx')
fixed

2017-01-08 02:09 UTC, jpbeltrami commented on excel.py
> +        print("<couldn't connect>")
fixed

2017-01-08 02:09 UTC, Aesirry commented on excel.py
> +        c.execute("INSERT INTO test (name, age) VALUES (%s, %s)", (item['name'], item['age']))
fixed

2017-01-08 02:24 UTC, Aesirry commented on excel.py
> +        result = urllib.parse.urlparse("postgres://4cebab44:4j602JWnaP3Yaw@db.nuodata.io:5432/4cebab44")
fixed

2017-01-08 05:02 UTC, rngadam commented on excel.py
> +#
empty comment?

2017-01-08 05:20 UTC, rngadam commented on excel.py
> +        result = urllib.parse.urlparse("postgres://USERNAME:PASSWORD@db.nuodata.io:5432/4cebab44")
I think this already works

2017-01-08 05:21 UTC, rngadam commented on excel.py
> +        print(e.pgerror)
this does not address the original comment asking to rethrow a custom exception

2017-01-08 05:21 UTC, rngadam commented on excel.py
> +    if workbook.endswith('.xlsx'):
useless/undesirable check

2017-01-08 05:23 UTC, rngadam commented on excel.py
> +    jdata = tojson('practice.xlsx')
and why not make this a parameter to post() too?  as the database parameter? and then, to make your tool really useful, parse command-line parameter instead:

https://docs.python.org/2/library/argparse.html

2017-01-08 05:23 UTC, rngadam commented on README.md
> +- tojson method found on: http://www.anthonydebarros.com/2013/02/05/get-json-from-excel-using-python-xlrd/
this does not explain how to use your utility.

2017-01-13 03:55 UTC, rngadam requested changes

2017-01-13 03:55 UTC, rngadam commented on README.md
> +pip install psycopg2
use a requirements.txt file:

https://pip.pypa.io/en/stable/user_guide/

2017-01-13 03:55 UTC, rngadam commented on README.md
> +$ python3 excel.py excel-file database-URI name of database
uppercase for parameters 

```
+$ python3 excel.py excel-file $DATABASE_URI $DATABASE_NAME
```

2017-01-13 03:55 UTC, rngadam commented on README.md
> +Download the excel.py file to any directory.
```
git clone repo
```

2017-01-13 03:55 UTC, rngadam commented on README.md
> +## License
use a LICENSE.TXT instead

2017-01-13 03:55 UTC, rngadam commented on excel.py
> +# TODO update readme with what this does, and usage example.
TODO as Github Issues instead

2017-01-13 03:55 UTC, rngadam commented on excel.py
> +    DB, c= connect(uri)
spacing before =

2017-01-13 03:55 UTC, rngadam commented on excel.py
> +##############################################
2 whitelines before start of new functions

2017-01-13 06:13 UTC, rngadam commented on excel.py
> +            query = "INSERT INTO %s (product_name, quantity) VALUES ('%s', %s)" % (tableName, item['product_name'], item['quantity'])
try to keep lines <80

2017-01-13 06:14 UTC, rngadam commented on requirements.txt
> +pip install psycopg2
shouldn't it just be the package?

2017-01-13 06:16 UTC, rngadam commented on README.md
> +pip install -r requirements.txt
test it in a clean python environment using virtualenv.

http://docs.python-guide.org/en/latest/dev/virtualenvs/

2017-01-13 06:27 UTC, Aesirry commented on excel.py
> +            query = "INSERT INTO %s (product_name, quantity) VALUES ('%s', %s)" % (tableName, item['product_name'], item['quantity'])
fixed

2017-01-13 06:37 UTC, Aesirry commented on README.md
> +pip install -r requirements.txt
done

2017-01-13 07:11 UTC, Aesirry commented on requirements.txt
> +pip install psycopg2
fixed

2017-04-17 06:38 UTC, merged